meta_product_name: "CoolCarb - calculateur de bilan carbone pour PME"
meta_title: "CoolCarb - Réduisez votre empreinte carbone!"
meta_description: "CoolCarb aide les PME à calculer leur bilan carbone, à définir leur plan d'action de réduction de leur empreinte carbone afin d'attirer de nouveaux clients et d'engager leurs employés dans des actions qui donnent du sens à leur métier"
meta_image: "cover.png" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
